// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOv1WvTYa0HT8aRmUTgVz1yZ7lAnGLKKg',
    appId: '1:254072743921:android:04f7e5013f791841468650',
    messagingSenderId: '254072743921',
    projectId: 'law-bot-3aaac',
    storageBucket: 'law-bot-3aaac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8v9znn2cwFakbfSyj4Bm6LgIAgiTm7Mg',
    appId: '1:254072743921:ios:dca665108e4a7ed9468650',
    messagingSenderId: '254072743921',
    projectId: 'law-bot-3aaac',
    storageBucket: 'law-bot-3aaac.appspot.com',
    iosClientId:
        '254072743921-n2p5j1iupm0fb1h8t7evt0clu2ibbs5r.apps.googleusercontent.com',
    iosBundleId: 'com.ahmttyydn.lawBot',
  );
}
